name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2016-10-05
version: '8.2.0'
core: '8.x'
project: 'drupal'
datestamp: 1475661292
